GetLatestTransform:
  source_frame_id: "selected_frame"
  target_frame_id: "world"

IsForceWithinThreshold:
  wrench_topic_name: "/force_torque_sensor_broadcaster/wrench"
  hand_frame_name: "manual_grasp_link"
  wrench_frame_name: "tool0"
  minimum_consecutive_wrench_values: 10
  force_threshold: 10.0  # Newtons

SetupMTCMoveAlongFrameAxis:
  arm_group_name: "manipulator"
  hand_frame_name: "manual_grasp_link"
  velocity_acceleration_scaling_factor: 0.05

AllowGripperCollisionWithOctomap:
  group_name: "gripper"
  object_name: "<octomap>"
  allow_collision: true

ForbidGripperCollisionWithOctomap:
  group_name: "gripper"
  object_name: "<octomap>"
  allow_collision: false
